#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.FARBE.Tasks.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AMBAR")]
	public partial class DBAmbarDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMusteri_Table(Musteri_Table instance);
    partial void UpdateMusteri_Table(Musteri_Table instance);
    partial void DeleteMusteri_Table(Musteri_Table instance);
    #endregion
		
		public DBAmbarDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AMBARConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbarDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbarDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Musteri_Table> Musteri_Tables
		{
			get
			{
				return this.GetTable<Musteri_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteri_Table")]
	public partial class Musteri_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Musteri_ID;
		
		private string _Musteri_Name;
		
		private string _Gorev;
		
		private string _User_name;
		
		private System.Nullable<System.DateTime> _Change_Date;
		
		private string _Modified_Person;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteri_IDChanging(int value);
    partial void OnMusteri_IDChanged();
    partial void OnMusteri_NameChanging(string value);
    partial void OnMusteri_NameChanged();
    partial void OnGorevChanging(string value);
    partial void OnGorevChanged();
    partial void OnUser_nameChanging(string value);
    partial void OnUser_nameChanged();
    partial void OnChange_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnChange_DateChanged();
    partial void OnModified_PersonChanging(string value);
    partial void OnModified_PersonChanged();
    #endregion
		
		public Musteri_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Musteri_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Musteri_ID
		{
			get
			{
				return this._Musteri_ID;
			}
			set
			{
				if ((this._Musteri_ID != value))
				{
					this.OnMusteri_IDChanging(value);
					this.SendPropertyChanging();
					this._Musteri_ID = value;
					this.SendPropertyChanged("Musteri_ID");
					this.OnMusteri_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Musteri_Name", DbType="VarChar(250)")]
		public string Musteri_Name
		{
			get
			{
				return this._Musteri_Name;
			}
			set
			{
				if ((this._Musteri_Name != value))
				{
					this.OnMusteri_NameChanging(value);
					this.SendPropertyChanging();
					this._Musteri_Name = value;
					this.SendPropertyChanged("Musteri_Name");
					this.OnMusteri_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorev", DbType="VarChar(100)")]
		public string Gorev
		{
			get
			{
				return this._Gorev;
			}
			set
			{
				if ((this._Gorev != value))
				{
					this.OnGorevChanging(value);
					this.SendPropertyChanging();
					this._Gorev = value;
					this.SendPropertyChanged("Gorev");
					this.OnGorevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_name", DbType="VarChar(200)")]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this.OnUser_nameChanging(value);
					this.SendPropertyChanging();
					this._User_name = value;
					this.SendPropertyChanged("User_name");
					this.OnUser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Change_Date
		{
			get
			{
				return this._Change_Date;
			}
			set
			{
				if ((this._Change_Date != value))
				{
					this.OnChange_DateChanging(value);
					this.SendPropertyChanging();
					this._Change_Date = value;
					this.SendPropertyChanged("Change_Date");
					this.OnChange_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_Person", DbType="VarChar(200)")]
		public string Modified_Person
		{
			get
			{
				return this._Modified_Person;
			}
			set
			{
				if ((this._Modified_Person != value))
				{
					this.OnModified_PersonChanging(value);
					this.SendPropertyChanging();
					this._Modified_Person = value;
					this.SendPropertyChanged("Modified_Person");
					this.OnModified_PersonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
